CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "bio" varchar,
  "hashedPassword" varchar NOT NULL,
  "avatar" varchar
);

CREATE TABLE "posts" (
  "postId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slug" varchar UNIQUE NOT NULL,
  "authorId" bigint NOT NULL,
  "title" varchar NOT NULL,
  "content" varchar NOT NULL,
  "tags" varchar[] DEFAULT '{}',
  "createdAt" timestamptz DEFAULT (now())
);

CREATE TABLE "files" (
  "fileId" varchar PRIMARY KEY,
  "postId" bigint NOT NULL,
  "name" varchar NOT NULL,
  "createdAt" timestamptz DEFAULT (now())
);

CREATE TABLE "likes" (
  "userId" bigint NOT NULL,
  "postId" bigint NOT NULL
);

CREATE TABLE "comments" (
  "userId" bigint NOT NULL,
  "postId" bigint NOT NULL,
  "content" varchar NOT NULL,
  "createdAt" timestamptz DEFAULT (now())
);

CREATE TABLE "follows" (
  "follower" bigint NOT NULL,
  "followee" bigint NOT NULL
);

CREATE INDEX ON "users" ("username");

CREATE INDEX ON "posts" ("slug");

CREATE INDEX ON "posts" ("authorId");

CREATE INDEX ON "posts" ("title");

CREATE INDEX ON "posts" USING GIN ("tags");

CREATE INDEX ON "files" ("postId");

CREATE INDEX ON "likes" ("userId");

CREATE INDEX ON "likes" ("postId");

CREATE INDEX ON "comments" ("userId");

CREATE INDEX ON "comments" ("postId");

CREATE INDEX ON "follows" ("follower");

CREATE INDEX ON "follows" ("followee");

ALTER TABLE "posts" ADD FOREIGN KEY ("authorId") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "files" ADD FOREIGN KEY ("postId") REFERENCES "posts" ("postId") ON DELETE CASCADE;

ALTER TABLE "likes" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "likes" ADD FOREIGN KEY ("postId") REFERENCES "posts" ("postId") ON DELETE CASCADE;

ALTER TABLE "comments" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "comments" ADD FOREIGN KEY ("postId") REFERENCES "posts" ("postId") ON DELETE CASCADE;

ALTER TABLE "follows" ADD FOREIGN KEY ("follower") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "follows" ADD FOREIGN KEY ("followee") REFERENCES "users" ("id") ON DELETE CASCADE;
